# Generated by Django 3.2.8 on 2021-11-30 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0002_auto_20211023_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_created']},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время комментария')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.article', verbose_name='Номер статьи')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
